In [ ]:
<h1, align=center> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数据科学引论 - Python之道 </h1>

<h1, align=center> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;第4课 数据分析入门 </h1>

<hr>

### 目录 
[**Numpy 库**](#NumPy-库)   
[**Pandas 库**](#Pandas-库)  
[**按国家和年份统计的CO2排放量**](#按国家和年份统计的CO2排放量)  
[**获取数据**](#获取数据)  
[**使用Pandas导入数据**](#使用-Pandas-导入数据)  
[**Dataframe的特性**](#Dataframe-的特性)  
[**对Dataframe求子集**](#对-Dataframe-求子集)  
[**按照条件求子集**](#按照条件求子集)  





<hr>

<h1, align="center">NumPy 库</h1>
__NumPy__: 
- 快速
- 多维数组 
- 向量化计算


### NumPy 多维数组
多维数组对象.  
用来在整块数据上执行数学操作. 

In [1]:
# to insert a library (a file consisting of Python code) use "import"
import numpy as np

#### 创建多维数组
- 使用 __array__ 函数.  
- 所有元素必须具有 __相同类型__ (同构)

In [2]:
data=np.array([[ 1.9526, -0.246 , -0.8856],
[ 0.5639, 0.2379, 0.9104]])
data

array([[ 1.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

每个数组都具有 __维数__ 和 __形状__ (一个表示每个维度尺寸的元素)

In [3]:
data.ndim

2

In [4]:
data.shape

(2, 3)

__dtype:__ 描述数组的数据类型的对象:


In [5]:
data.dtype

dtype('float64')

__empty__, __arange__ , __zeros__ 和 **ones** 数组

In [6]:
data1=np.empty((3,2))
data1

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [9]:
data0=np.zeros((3,2))
data0

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [10]:
data3=np.arange(10)
data3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### <span style="color: red">轮到你了:</span> 
创建一个 2x4 的数组，数组中元素都是 1，然后获取该数组的数据类型和形状。

In [16]:
#You code
data4 = np.ones((2,4), dtype=np.int32)
print(data4)
print(data4.dtype)
print(data4.shape)


[[1 1 1 1]
 [1 1 1 1]]
int32
(2, 4)


#### 数据类型

In [ ]:
data=np.array([1.25, -9.6, 42], dtype=np.string_)
data

可以将该数组强制类型转换为浮点数类型

In [ ]:
data.astype(np.float32)

<hr></hr>
<div class="alert alert-success alertsuccess" style="margin-top: 0px">
<h4> [tip] 强制类型转换后，为什么-9.6变成了-9.60000038？ </h4>
<p></p>
这是因为浮点数只是一种近似表达，它几乎总是会存在误差：
<li>简单地讲，浮点数中每一位都表示2的-n次方，32位浮点数最高精度就是2的-32次方。我们可以这样理解，浮点数的表示机制就是用一系列离散的点来表示连续的数轴，点与点之间的距离就是浮点数最高精度位所能表示的数字。除非希望表示的浮点数正好落在这些点上，否则误差总是存在，它总是会近似地表示成最靠近它的某个点所表示的数字。</li>
<li>回到-9.6的例子，就是因为浮点数机制无法精确表示它，但是在能够精确表示的数字中，-9.60000038离它最近，因此用-9.60000038近似表示它。</li>
<p></p>
浮点数的这种机制告诉我们，需要精确表示数据时，不要使用浮点数。
<li>例如，在表示货币金额时，通常会选择使用整数来表示，单位为分，而不会选择使用浮点数来表示。如果我们留意第三方支付服务的接口，就会发现它们清一色都是使用单位为分的整数来表示的。</li>
<p></p>
</div>
<hr></hr>

### 操作

In [17]:
arr= np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

#### 算数操作

In [18]:
arr*2

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [20]:
arr*arr

AttributeError: 'numpy.ndarray' object has no attribute 'mulmat'

<hr></hr>
<div class="alert alert-success alertsuccess" style="margin-top: 0px">
<h4> [tip] **arr*arr**执行的不是矩阵乘法？ </h4>
<p></p>
很遗憾，尽管多维数组看起来就是矩阵，但是**arr*arr**执行的不是矩阵乘法。<br/>
**arr*arr**执行的是将两个矩阵对应位置上元素的乘积作为结果矩阵中对应位置上的元素。所以：
<li>尽管arr是一个2×3的矩阵，按照矩阵乘法的规则，**arr*arr**非法，但是在Python中这是合法操作。</li>
<li>**arr*arr**产生的结果仍旧是一个2×3的矩阵，其中每个元素的值都是arr中对应元素的平方值。</li>
<p></p>
</div>
<hr></hr>

### 索引和切片
用来选择数据子集或单个元素

In [21]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

与Python的列表相同:

In [22]:
arr[5]

5

In [ ]:
arr[5:8]

可以将某个值赋给一个切片:

In [ ]:
arr[5:8] = 12
arr

In [ ]:
arr[5:]

在多维数组中，单个索引对应的元素都不再是具体的值，而是一个数组

In [23]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[2]

array([7, 8, 9])

In [25]:
arr2d[0][2]   # also: arr2d[0, 2]

3

In [26]:
arr2d[2:]

array([[7, 8, 9]])

切片总是按照先切第0维，再切第1维，以此类推的顺序切。  
例如，下面的代码表示先切出前两行，然后再切出后两列：

In [35]:
arr2d[:2, 1:]

array([1, 2, 3])

### 布尔索引

In [36]:
data=np.random.rand(7,4)
data

array([[ 0.52742265,  0.51358341,  0.65456691,  0.15302209],
       [ 0.59542883,  0.6381207 ,  0.09811741,  0.44969032],
       [ 0.3448822 ,  0.32029788,  0.96003997,  0.31254118],
       [ 0.7259944 ,  0.9473172 ,  0.11402494,  0.51986073],
       [ 0.9804589 ,  0.3101658 ,  0.1994008 ,  0.71057957],
       [ 0.45362085,  0.70877795,  0.08378038,  0.7018127 ],
       [ 0.20543583,  0.28394661,  0.52704634,  0.82922495]])

In [ ]:
data > 0.4    # Comparison Operators: ==, !=, &, |

In [ ]:
data[(data>0.4)]

### 函数

In [37]:
arr = np.arange(5)
np.sqrt(arr)   #squar root function

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

In [38]:

np.exp(arr)   #exponentiation function

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [39]:
np.mean(arr) #average function

2.0

### <span style="color: red">轮到你了:</span> 

创建一个3x2的numpy数组 (使用 __ones__ 函数), 然后选择其中的第2行

In [42]:
## YOUR CODE BELOW
myturn = np.ones((3,2))
myturn[2]


array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

<h1, align="center">Pandas 库</h1>

Pandas
- 可用于大多数类型的数据分析
- 可对结构化或表格化数据进行分析
- 高层数据结构
- 构建在NumPy之上  
- 可进行时间序列操作


对象:  
- Series  
- DataFrame  



首先, 导入Pandas包

In [43]:
import pandas as pd

### Series

Series是一种类似一维数组的对象，其中包含了一个数据数组(可以具有任何NumPy的数据类型)和一个被称为索引的由数据标号构成的关联数组。

In [44]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [45]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [47]:
'b' in obj2

False

### DataFrame
- 表示一种类似电子表格的数据结构
- 每一列都可以包含不同的值类型(数值型, 字符串, 布尔型, 等等)
- 具有行和列索引

<h1, align="center">按国家和年份统计的CO2排放量</h1>

二氧化碳排放源自燃烧化石燃料和水泥制造，包含了在固体、液体和气体燃料消耗以及放空燃烧过程中所产生的二氧化碳

http://data.worldbank.org/indicator/EN.ATM.CO2E.PC/

<h2, align=center>获取数据</h2>

这些数据可以从世界银行(World Bank) [链接](http://data.worldbank.org/indicator/EN.ATM.CO2E.PC/) 或者从 Box [链接](https://ibm.box.com/shared/static/3yzxbbizo49bkl8cnjw15tymzfwkycj4.csv) 上下载

#### 我们在linux下可以使用bash命令 `wget` 从链接处获取 csv 文件

In [ ]:
!wget --output-document /resources/data/co2emissions.csv https://ibm.box.com/shared/static/3yzxbbizo49bkl8cnjw15tymzfwkycj4.csv

<hr>

<h2, align=center>使用 Pandas 导入数据</h2>

#### 导入所需的 `pandas` 库

In [48]:
import pandas as pd

#### 使用 `pd.read_csv` 导入数据

In [50]:
data = pd.read_csv("./data/co2emissions.csv", skiprows = 4)

In [51]:
type(data) #Checks the type of object

pandas.core.frame.DataFrame

In [52]:
data

Country Name Country Code  \
0                             Aruba          ABW   
1                           Andorra          AND   
2                       Afghanistan          AFG   
3                            Angola          AGO   
4                           Albania          ALB   
5                        Arab World          ARB   
6              United Arab Emirates          ARE   
7                         Argentina          ARG   
8                           Armenia          ARM   
9                    American Samoa          ASM   
10              Antigua and Barbuda          ATG   
11                        Australia          AUS   
12                          Austria          AUT   
13                       Azerbaijan          AZE   
14                          Burundi          BDI   
15                          Belgium          BEL   
16                            Benin          BEN   
17                     Burkina Faso          BFA   
18                       Bangladesh          BGD   
19                         Bulgaria          BGR   
20                          Bahrain          BHR   
21                     Bahamas, The          BHS   
22           Bosnia and Herzegovina          BIH   
23                          Belarus          BLR   
24                           Belize          BLZ   
25                          Bermuda          BMU   
26                          Bolivia          BOL   
27                           Brazil          BRA   
28                         Barbados          BRB   
29                Brunei Darussalam          BRN   
..                              ...          ...   
219                        Thailand          THA   
220                      Tajikistan          TJK   
221                    Turkmenistan          TKM   
222                     Timor-Leste          TLS   
223                           Tonga          TON   
224             Trinidad and Tobago          TTO   
225                         Tunisia          TUN   
226                          Turkey          TUR   
227                          Tuvalu          TUV   
228                   Taiwan, China          TWN   
229                        Tanzania          TZA   
230                          Uganda          UGA   
231                         Ukraine          UKR   
232             Upper middle income          UMC   
233                         Uruguay          URY   
234                   United States          USA   
235                      Uzbekistan          UZB   
236  St. Vincent and the Grenadines          VCT   
237                   Venezuela, RB          VEN   
238           Virgin Islands (U.S.)          VIR   
239                         Vietnam          VNM   
240                         Vanuatu          VUT   
241              West Bank and Gaza          PSE   
242                           World          WLD   
243                           Samoa          WSM   
244                     Yemen, Rep.          YEM   
245                    South Africa          ZAF   
246                Congo, Dem. Rep.          COD   
247                          Zambia          ZMB   
248                        Zimbabwe          ZWE   

                             Indicator Name  Indicator Code       1960  \
0    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN   
1    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN   
2    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.046068   
3    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.104357   
4    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.258195   
5    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.643964   
6    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.118786   
7    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   2.367473   
8    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN   
9    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.P

<h2, align=center>Dataframe 的操作</h2>

#### 使用 `head` 显示 `data`  的前5行

In [53]:
data.head()

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1      Andorra          AND  CO2 emissions (metric tons per capita)   
2  Afghanistan          AFG  CO2 emissions (metric tons per capita)   
3       Angola          AGO  CO2 emissions (metric tons per capita)   
4      Albania          ALB  CO2 emissions (metric tons per capita)   

   Indicator Code      1960      1961      1962      1963      1964      1965  \
0  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   
1  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   
2  EN.ATM.CO2E.PC  0.046068  0.053615  0.073781  0.074251  0.086317  0.101499   
3  EN.ATM.CO2E.PC  0.104357  0.084718  0.216025  0.206877  0.216174  0.206089   
4  EN.ATM.CO2E.PC  1.258195  1.374186  1.439956  1.181681  1.111742  1.166099   

      ...            2007       2008       2009       2010       2011  2012  \
0     ...       25.613715  24.750133  24.876706  24.182702  23.922412   NaN   
1     ...        6.350868   6.296125   6.049173   6.124770   5.968685   NaN   
2     ...        0.088141   0.158962   0.249074   0.302936   0.425262   NaN   
3     ...        1.311096   1.369425   1.430873   1.401654   1.354008   NaN   
4     ...        1.507536   1.580113   1.533178   1.515632   1.607038   NaN   

   2013  2014  2015  Unnamed: 60  
0   NaN   NaN   NaN          NaN  
1   NaN   NaN   NaN          NaN  
2   NaN   NaN   NaN          NaN  
3   NaN   NaN   NaN          NaN  
4   NaN   NaN   NaN          NaN  

[5 rows x 61 columns]

#### 使用 `head` 获取前2行

In [ ]:
data.head(2)

In [ ]:
data.head(n=1)

### 不记得需要向函数传递什么参数了？可以使用 `?`

In [54]:
#To close help window, press q
? data.head

#### 显示最后3行数据

In [ ]:
data.tail(3)

<hr>

<h2, align=center>Dataframe 的特性</h2>

#### 有多少行和多少列?

In [55]:
data.shape #(rows, columns)

(249, 61)

In [57]:
data.describe()

/home/irving/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)


1960        1961        1962        1963        1964        1965  \
count  180.000000  181.000000  182.000000  183.000000  188.000000  188.000000   
mean     2.147848    2.273331    2.382827    2.925962    3.076591    3.203665   
std      4.348322    4.542379    4.889944    8.741776    8.776709    8.964691   
min      0.008022    0.007897    0.008481    0.009390    0.011598    0.011910   
25%           NaN         NaN         NaN         NaN         NaN         NaN   
50%           NaN         NaN         NaN         NaN         NaN         NaN   
75%           NaN         NaN         NaN         NaN         NaN         NaN   
max     36.685183   36.583778   42.637118   99.575940   92.969565   85.563167   

             1966        1967        1968        1969     ...       \
count  188.000000  188.000000  187.000000  188.000000     ...        
mean     3.216921    3.287063    3.515189    4.136080     ...        
std      8.309355    7.504329    7.450713   10.208690     ...        
min      0.013258    0.011800    0.015594    0.016116     ...        
25%           NaN         NaN         NaN         NaN     ...        
50%           NaN         NaN         NaN         NaN     ...        
75%           NaN         NaN         NaN         NaN     ...        
max     78.734608   77.629183   76.104350   99.840439     ...        

             2007        2008        2009        2010        2011  2012  2013  \
count  232.000000  232.000000  232.000000  232.000000  232.000000   0.0   0.0   
mean     5.023040    4.980116    4.755409    4.911618    4.884828   NaN   NaN   
std      6.598310    6.328807    5.975440    6.100080    6.051724   NaN   NaN   
min      0.021964    0.021615    0.020868    0.020542    0.021350   NaN   NaN   
25%           NaN         NaN         NaN         NaN         NaN   NaN   NaN   
50%           NaN         NaN         NaN         NaN         NaN   NaN   NaN   
75%           NaN         NaN         NaN         NaN         NaN   NaN   NaN   
max     55.336800   48.601620   44.836401   42.639076   44.018926   NaN   NaN   

       2014  2015  Unnamed: 60  
count   0.0   0.0          0.0  
mean    NaN   NaN          NaN  
std     NaN   NaN          NaN  
min     NaN   NaN          NaN  
25%     NaN   NaN          NaN  
50%     NaN   NaN          NaN  
75%     NaN   NaN          NaN  
max     NaN   NaN          NaN  

[8 rows x 57 columns]

#### 列名有哪些?

In [58]:
data.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', 'Unnamed: 60'],
      dtype='object')

#### 第一列的名字是什么?

In [59]:
data.columns[0]

'Country Name'

#### 第一列和第二列的名字是什么?

In [60]:
data.columns[[0,1]]

Index(['Country Name', 'Country Code'], dtype='object')

<hr>

## 复习

### <span style="color: red">轮到你了:</span> 

#### 打印 `data` 的前3行

In [62]:
## YOUR CODE BELOW
data.head(3)


Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1      Andorra          AND  CO2 emissions (metric tons per capita)   
2  Afghanistan          AFG  CO2 emissions (metric tons per capita)   

   Indicator Code      1960      1961      1962      1963      1964      1965  \
0  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   
1  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   
2  EN.ATM.CO2E.PC  0.046068  0.053615  0.073781  0.074251  0.086317  0.101499   

      ...            2007       2008       2009       2010       2011  2012  \
0     ...       25.613715  24.750133  24.876706  24.182702  23.922412   NaN   
1     ...        6.350868   6.296125   6.049173   6.124770   5.968685   NaN   
2     ...        0.088141   0.158962   0.249074   0.302936   0.425262   NaN   

   2013  2014  2015  Unnamed: 60  
0   NaN   NaN   NaN          NaN  
1   NaN   NaN   NaN          NaN  
2   NaN   NaN   NaN          NaN  

[3 rows x 61 columns]

#### 打印第一列和最后一列的名字

In [64]:
## YOUR CODE BELOW
print(data.columns[0])
print(data.columns[-1])



Country Name
Unnamed: 60


<hr>

<h2, align=center>对 Dataframe 求子集</h2>

### 选择列

#### 按名字选择列:

In [12]:
data['Country Name']

0                                                  Aruba
1                                            Afghanistan
2                                                 Angola
3                                                Albania
4                                                Andorra
5                                             Arab World
6                                   United Arab Emirates
7                                              Argentina
8                                                Armenia
9                                         American Samoa
10                                   Antigua and Barbuda
11                                             Australia
12                                               Austria
13                                            Azerbaijan
14                                               Burundi
15                                               Belgium
16                                                 Benin
17                             

#### 按列号选择列:

In [65]:
data[data.columns[0]]

'Country Name'

#### 选择最后一列:

In [14]:
data[data.columns[-1]]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
21    NaN
22    NaN
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
28    NaN
29    NaN
       ..
234   NaN
235   NaN
236   NaN
237   NaN
238   NaN
239   NaN
240   NaN
241   NaN
242   NaN
243   NaN
244   NaN
245   NaN
246   NaN
247   NaN
248   NaN
249   NaN
250   NaN
251   NaN
252   NaN
253   NaN
254   NaN
255   NaN
256   NaN
257   NaN
258   NaN
259   NaN
260   NaN
261   NaN
262   NaN
263   NaN
Name: Unnamed: 61, dtype: float64

#### 按名字选择由多列构成子集

In [15]:
data[['Country Name', 'Country Code']] 

Country Name Country Code
0                                                Aruba          ABW
1                                          Afghanistan          AFG
2                                               Angola          AGO
3                                              Albania          ALB
4                                              Andorra          AND
5                                           Arab World          ARB
6                                 United Arab Emirates          ARE
7                                            Argentina          ARG
8                                              Armenia          ARM
9                                       American Samoa          ASM
10                                 Antigua and Barbuda          ATG
11                                           Australia          AUS
12                                             Austria          AUT
13                                          Azerbaijan          AZE
14                                             Burundi          BDI
15                                             Belgium          BEL
16                                               Benin          BEN
17                                        Burkina Faso          BFA
18                                          Bangladesh          BGD
19                                            Bulgaria          BGR
20                                             Bahrain          BHR
21                                        Bahamas, The          BHS
22                              Bosnia and Herzegovina          BIH
23                                             Belarus          BLR
24                                              Belize          BLZ
25                                             Bermuda          BMU
26                                             Bolivia          BOL
27                                              Brazil          BRA
28                                            Barbados          BRB
29                                   Brunei Darussalam          BRN
..                                                 ...          ...
234  Latin America & the Caribbean (IDA & IBRD coun...          TLA
235                                        Timor-Leste          TLS
236  Middle East & North Africa (IDA & IBRD countries)          TMN
237                                              Tonga          TON
238                            South Asia (IDA & IBRD)          TSA
239          Sub-Saharan Africa (IDA & IBRD countries)          TSS
240                                Trinidad and Tobago          TTO
241                                            Tunisia          TUN
242                                             Turkey          TUR
243                                             Tuvalu          TUV
244                                           Tanzania          TZA
245                                             Uganda          UGA
246                                            Ukraine          UKR
247                                Upper middle income          UMC
248                                            Uruguay          URY
249                                      United States          USA
250                                         Uzbekistan          UZB
251                     St. Vincent and the Grenadines          VCT
252                                      Venezuela, RB          VEN
253                             British Virgin Islands          VGB
254                              Virgin Islands (U.S.)          VIR
255                                            Vietnam          VNM
256                                            Vanuatu          VUT
257                                              World          WLD
258                                              Samoa          WSM
259                                             Kosovo          XKX
260                                        Yemen, Rep.          YEM
261                           

### 选择行

若干种方式:

In [16]:
data[0:2] #First and second row

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1  Afghanistan          AFG  CO2 emissions (metric tons per capita)   

   Indicator Code     1960      1961      1962      1963      1964      1965  \
0  EN.ATM.CO2E.PC      NaN       NaN       NaN       NaN       NaN       NaN   
1  EN.ATM.CO2E.PC  0.04606  0.053604  0.073765  0.074233  0.086292  0.101467   

      ...            2008       2009       2010       2011       2012  \
0     ...       26.230847  25.915833  24.670529  24.505835  13.155542   
1     ...        0.154101   0.241723   0.293837   0.412017   0.350371   

       2013      2014  2015  2016  Unnamed: 61  
0  8.351294  8.408363   NaN   NaN          NaN  
1  0.315602  0.299445   NaN   NaN          NaN  

[2 rows x 62 columns]

In [17]:
data[:2] 

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
1  Afghanistan          AFG  CO2 emissions (metric tons per capita)   

   Indicator Code     1960      1961      1962      1963      1964      1965  \
0  EN.ATM.CO2E.PC      NaN       NaN       NaN       NaN       NaN       NaN   
1  EN.ATM.CO2E.PC  0.04606  0.053604  0.073765  0.074233  0.086292  0.101467   

      ...            2008       2009       2010       2011       2012  \
0     ...       26.230847  25.915833  24.670529  24.505835  13.155542   
1     ...        0.154101   0.241723   0.293837   0.412017   0.350371   

       2013      2014  2015  2016  Unnamed: 61  
0  8.351294  8.408363   NaN   NaN          NaN  
1  0.315602  0.299445   NaN   NaN          NaN  

[2 rows x 62 columns]

In [18]:
data.iloc[[0,2]] #First and third rows

Country Name Country Code                          Indicator Name  \
0        Aruba          ABW  CO2 emissions (metric tons per capita)   
2       Angola          AGO  CO2 emissions (metric tons per capita)   

   Indicator Code      1960      1961      1962      1963      1964      1965  \
0  EN.ATM.CO2E.PC       NaN       NaN       NaN       NaN       NaN       NaN   
2  EN.ATM.CO2E.PC  0.097472  0.079038  0.201289  0.192535  0.201003  0.191528   

      ...            2008       2009       2010       2011       2012  \
0     ...       26.230847  25.915833  24.670529  24.505835  13.155542   
2     ...        1.181527   1.232495   1.243406   1.252789   1.330843   

       2013      2014  2015  2016  Unnamed: 61  
0  8.351294  8.408363   NaN   NaN          NaN  
2  1.254617  1.291328   NaN   NaN          NaN  

[2 rows x 62 columns]

In [19]:
data[0:2]['Country Name']

0          Aruba
1    Afghanistan
Name: Country Name, dtype: object

In [67]:
data.ix[0:3,1:4] #First row
? data.iloc

#### 选择最后一行

In [21]:
data.iloc[-1]

Country Name                                    Zimbabwe
Country Code                                         ZWE
Indicator Name    CO2 emissions (metric tons per capita)
Indicator Code                            EN.ATM.CO2E.PC
1960                                                 NaN
1961                                                 NaN
1962                                                 NaN
1963                                                 NaN
1964                                             1.04775
1965                                             1.18236
1966                                             1.32798
1967                                              1.1274
1968                                             1.31595
1969                                             1.34763
1970                                             1.57715
1971                                             1.63368
1972                                             1.48578
1973                           

<h2, align=center>按照条件求子集</h2>

回忆: 有多种逻辑操作符可以用来创建逻辑语句:

In [22]:
1 == 2

False

In [23]:
"Me" != "You"

True

In [24]:
1000 > 1

True

在将一条逻辑语句应用到数组上时，会返回一个由True/False构成的数组，取值对应于该逻辑语句。

In [68]:
import numpy as np
my_range = np.array(range(1,100))
my_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
result = my_range > 50
result

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

然后，我们可以使用这个True/False数组来返回只包含原来数组中对应 true 的那些值。

In [27]:
my_range[result]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 基于单一条件选择行

In [28]:
data['Country Name']

0                                                  Aruba
1                                            Afghanistan
2                                                 Angola
3                                                Albania
4                                                Andorra
5                                             Arab World
6                                   United Arab Emirates
7                                              Argentina
8                                                Armenia
9                                         American Samoa
10                                   Antigua and Barbuda
11                                             Australia
12                                               Austria
13                                            Azerbaijan
14                                               Burundi
15                                               Belgium
16                                                 Benin
17                             

In [29]:
#Data where the country name is Albania. Returns True/False
data['Country Name'] == 'Albania'

0      False
1      False
2      False
3       True
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
Name: Country Name, dtype: bool

In [73]:
data[data['Country Code'] == 'CHN'] #Subset based on condition

Country Name Country Code                          Indicator Name  \
38        China          CHN  CO2 emissions (metric tons per capita)   

    Indicator Code      1960      1961      1962      1963      1964  \
38  EN.ATM.CO2E.PC  1.170381  0.836047  0.661428  0.640002  0.625646   

        1965     ...           2007      2008      2009      2010      2011  \
38  0.665524     ...       5.153564  5.311152  5.778143  6.172489  6.710302   

    2012  2013  2014  2015  Unnamed: 60  
38   NaN   NaN   NaN   NaN          NaN  

[1 rows x 61 columns]

#### 基于多重条件选择行

In [31]:
data[(data['Country Name'] == 'China') & (data['Country Code'] == 'CHN')]

Country Name Country Code                          Indicator Name  \
38        China          CHN  CO2 emissions (metric tons per capita)   

    Indicator Code      1960      1961      1962      1963      1964  \
38  EN.ATM.CO2E.PC  1.170381  0.836047  0.661428  0.640002  0.625646   

        1965     ...           2008      2009     2010      2011      2012  \
38  0.665524     ...       5.701915  6.010102  6.56052  7.241515  7.424751   

        2013      2014  2015  2016  Unnamed: 61  
38  7.557211  7.543908   NaN   NaN          NaN  

[1 rows x 62 columns]

#### 为什么下面的语句不会返回任何符合条件的行?

In [32]:
data[(data['Country Name'] == 'Canada') & (data['Country Code'] == 'CHN')]

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, Unnamed: 61]
Index: []

[0 rows x 62 columns]

### 按行和列选择数据

下面的代码产生什么结果?

In [82]:
data[['Country Name', 'Country Code', '2010']][16:21]
data.ix[1]

Country Name                                     Andorra
Country Code                                         AND
Indicator Name    CO2 emissions (metric tons per capita)
Indicator Code                            EN.ATM.CO2E.PC
1960                                                 NaN
1961                                                 NaN
1962                                                 NaN
1963                                                 NaN
1964                                                 NaN
1965                                                 NaN
1966                                                 NaN
1967                                                 NaN
1968                                                 NaN
1969                                                 NaN
1970                                                 NaN
1971                                                 NaN
1972                                                 NaN
1973                           

<hr>

## 复习

### <span style="color: red">轮到你了:</span> 
<h3>查找法国和德国在2010和2011年的人均CO2排放量</h3>

你应该产生像下面这样的输出:

<img src = https://ibm.box.com/shared/static/23drzeu5h2uydwhb0un9qa4jq9yzrjbi.png, width = 300>

In [ ]:
#hint
# data['Country Name']== ??
# data[['Country Name', '2010', '2011']].iloc[[??,??]]

In [91]:
## YOUR CODE BELOW
data[['Country Name','2010','2011']][(data['Country Name']== 'Germany') | (data['Country Name']=='France')]


Country Name      2010      2011
52      Germany  9.179817  8.917833
73       France  5.496707  5.185043

<hr>